name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build & Push
      uses: mr-smithers-excellent/docker-build-push@v3.3
      with:
        image: nimamahmoudi/latex-builder
        directory: ./
        dockerfile: ./Dockerfile
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}