name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build & Push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: nimamahmoudi/latex-builder
        cache_froms: node:10-slim,nimamahmoudi/latex-builder
        path: ./
        dockerfile: ./Dockerfile
        registry: docker.io
        push: true
        tag_with_ref: true
        tag_with_sha: true
